"""url isn't unique, link add total

Revision ID: 0002
Revises: 0001
Create Date: 2026-04-15 18:12:01.249451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('total', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('link_url_key'), 'link', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('link_url_key'), 'link', ['url'], postgresql_nulls_not_distinct=False)
    op.drop_column('link', 'total')
    # ### end Alembic commands ###
