"""added expires_at, is_active, user_id and relationship(user) in link table and relationship(link) in user table

Revision ID: 0007
Revises: 0006
Create Date: 2026-05-06 09:16:29.790275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('link', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('link', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'link', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_column('link', 'user_id')
    op.drop_column('link', 'is_active')
    op.drop_column('link', 'expires_at')
    # ### end Alembic commands ###
