"""user_id in token is not unique

Revision ID: 0008
Revises: 0007
Create Date: 2026-05-16 18:31:06.729929

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('token_user_id_key'), 'token', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('token_user_id_key'), 'token', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
